# Secrets used by the web service and sync job. Values are written here from random/TF inputs;
# values that come from outside (Drive token, OAuth client secret) are managed out-of-band by
# the deploy pipeline using `gcloud secrets versions add`. We DECLARE the secrets in Terraform
# so IAM bindings are stable, but we don't fight the deploy pipeline over their contents.

# --- Session signing key (random, generated by TF) ---

resource "random_password" "session_secret" {
  length  = 64
  special = true
}

resource "google_secret_manager_secret" "session_secret" {
  secret_id = "hcw-session-secret"
  replication { auto {} }
  depends_on = [google_project_service.services]
}

resource "google_secret_manager_secret_version" "session_secret" {
  secret      = google_secret_manager_secret.session_secret.id
  secret_data = random_password.session_secret.result
}

# --- DB password (generated alongside the SQL user) ---

resource "google_secret_manager_secret" "db_password" {
  secret_id  = "hcw-db-password"
  replication { auto {} }
  depends_on = [google_project_service.services]
}

resource "google_secret_manager_secret_version" "db_password" {
  secret      = google_secret_manager_secret.db_password.id
  secret_data = random_password.app_db.result
}

# --- Google OAuth client secret (managed out-of-band) ---

resource "google_secret_manager_secret" "google_oauth_client_secret" {
  secret_id  = "hcw-google-oauth-client-secret"
  replication { auto {} }
  depends_on = [google_project_service.services]

  lifecycle {
    ignore_changes = [labels]
  }
}

# --- Drive OAuth token JSON (managed out-of-band by the deploy pipeline) ---

resource "google_secret_manager_secret" "drive_token" {
  secret_id  = "hcw-drive-token"
  replication { auto {} }
  depends_on = [google_project_service.services]
}

# --- IAM: which SAs can read which secrets ---

# Web service: session secret, DB password, OAuth client secret.
locals {
  web_secrets = {
    session_secret             = google_secret_manager_secret.session_secret.id
    db_password                = google_secret_manager_secret.db_password.id
    google_oauth_client_secret = google_secret_manager_secret.google_oauth_client_secret.id
  }
  sync_secrets = {
    db_password  = google_secret_manager_secret.db_password.id
    drive_token  = google_secret_manager_secret.drive_token.id
  }
}

resource "google_secret_manager_secret_iam_member" "web_secret_access" {
  for_each  = local.web_secrets
  secret_id = each.value
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.web.email}"
}

resource "google_secret_manager_secret_iam_member" "sync_secret_access" {
  for_each  = local.sync_secrets
  secret_id = each.value
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.sync.email}"
}

# Deployer needs to add new versions of the out-of-band secrets during deploys.
resource "google_secret_manager_secret_iam_member" "deployer_oauth_client_writer" {
  secret_id = google_secret_manager_secret.google_oauth_client_secret.id
  role      = "roles/secretmanager.secretVersionAdder"
  member    = "serviceAccount:${google_service_account.deployer.email}"
}

resource "google_secret_manager_secret_iam_member" "deployer_drive_token_writer" {
  secret_id = google_secret_manager_secret.drive_token.id
  role      = "roles/secretmanager.secretVersionAdder"
  member    = "serviceAccount:${google_service_account.deployer.email}"
}
